toolbar: 'image | undo redo | bold italic forecolor
| alignleft aligncenter alignright alignjustify 
| bullist numlist outdent indent | removeformat '
tinymce . init ({ selector : 'textarea' , // change this value according to your HTML file_browser_callback_types : 'file image media' }); 
plugins:
  - image
  - link